export const laender = [
  "Afghanistan",
  "Åland",
  "Albanien",
  "Algerien",
  "Amerikanisch-Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarktis",
  "Antigua und Barbuda",
  "Argentinien",
  "Armenien",
  "Aruba",
  "Australien",
  "Aserbaidschan",
  "Bahamas",
  "Bahrain",
  "Bangladesch",
  "Barbados",
  "Belarus",
  "Belgien",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivien",
  "Bosnien und Herzegowina",
  "Botswana",
  "Bouvetinsel",
  "Brasilien",
  "Britisches Territorium im Indischen Ozean",
  "Brunei",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Kambodscha",
  "Kamerun",
  "Kanada",
  "Karibische Niederlande",
  "Kaimaninseln",
  "Zentralafrikanische Republik",
  "Tschad",
  "Chile",
  "China",
  "Weihnachtsinsel",
  "Kokosinseln",
  "Kolumbien",
  "Komoren",
  "Republik Kongo",
  "Demokratische Republik Kongo",
  "Cookinseln",
  "Costa Rica",
  "Kroatien",
  "Kuba",
  "Curaçao",
  "Zypern",
  "Tschechien",
  "Elfenbeinküste",
  "Dänemark",
  "Dschibuti",
  "Dominica",
  "Dominikanische Republik",
  "Ecuador",
  "Ägypten",
  "El Salvador",
  "Äquatorialguinea",
  "Eritrea",
  "Estland",
  "Eswatini",
  "Äthiopien",
  "Falklandinseln",
  "Färöer",
  "Fidschi",
  "Finnland",
  "Frankreich",
  "Französisch-Guayana",
  "Französisch-Polynesien",
  "Französische Süd- und Antarktisgebiete",
  "Gabun",
  "Gambia",
  "Georgien",
  "Ghana",
  "Gibraltar",
  "Griechenland",
  "Grönland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard und McDonaldinseln",
  "Honduras",
  "Hongkong",
  "Ungarn",
  "Island",
  "Indien",
  "Indonesien",
  "Iran",
  "Irak",
  "Irland",
  "Isle of Man",
  "Israel",
  "Italien",
  "Jamaika",
  "Japan",
  "Jersey",
  "Jordanien",
  "Kasachstan",
  "Kenia",
  "Kiribati",
  "Nordkorea",
  "Südkorea",
  "Kosovo",
  "Kuwait",
  "Kirgisistan",
  "Laos",
  "Lettland",
  "Libanon",
  "Lesotho",
  "Liberia",
  "Libyen",
  "Liechtenstein",
  "Litauen",
  "Luxemburg",
  "Macau",
  "Nordmazedonien",
  "Madagaskar",
  "Malawi",
  "Malaysia",
  "Malediven",
  "Mali",
  "Malta",
  "Marshallinseln",
  "Martinique",
  "Mauretanien",
  "Mauritius",
  "Mayotte",
  "Mexiko",
  "Mikronesien",
  "Moldau",
  "Monaco",
  "Mongolei",
  "Montenegro",
  "Montserrat",
  "Marokko",
  "Mosambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niederlande",
  "Neukaledonien",
  "Neuseeland",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolkinsel",
  "Nördliche Marianen",
  "Norwegen",
  "Oman",
  "Pakistan",
  "Palau",
  "Palästina",
  "Panama",
  "Papua-Neuguinea",
  "Paraguay",
  "Peru",
  "Philippinen",
  "Pitcairninseln",
  "Polen",
  "Portugal",
  "Puerto Rico",
  "Katar",
  "Réunion",
  "Rumänien",
  "Russland",
  "Ruanda",
  "Saint-Barthélemy",
  "St. Helena",
  "St. Kitts und Nevis",
  "St. Lucia",
  "Saint-Martin",
  "Saint-Pierre und Miquelon",
  "St. Vincent und die Grenadinen",
  "Samoa",
  "San Marino",
  "São Tomé und Príncipe",
  "Saudi-Arabien",
  "Senegal",
  "Serbien",
  "Seychellen",
  "Sierra Leone",
  "Singapur",
  "Sint Maarten",
  "Slowakei",
  "Slowenien",
  "Salomonen",
  "Somalia",
  "Südafrika",
  "Südgeorgien und die Südlichen Sandwichinseln",
  "Südsudan",
  "Spanien",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Spitzbergen und Jan Mayen",
  "Schweden",
  "Syrien",
  "Taiwan",
  "Tadschikistan",
  "Tansania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad und Tobago",
  "Tunesien",
  "Türkei",
  "Turkmenistan",
  "Turks- und Caicosinseln",
  "Tuvalu",
  "Kleinere Amerikanische Überseeinseln",
  "Uganda",
  "Ukraine",
  "Vereinigte Arabische Emirate",
  "Vereinigtes Königreich",
  "Vereinigte Staaten",
  "Uruguay",
  "Usbekistan",
  "Vanuatu",
  "Vatikanstadt",
  "Venezuela",
  "Vietnam",
  "Britische Jungferninseln",
  "Amerikanische Jungferninseln",
  "Wallis und Futuna",
  "Westsahara",
  "Jemen",
  "Sambia",
  "Simbabwe",
].sort((a, b) => a.localeCompare(b, "de"));